### ISSUE TITLE
style(Legends): ajout de marges et centrage

### ISSUE THREAD

**Issue by elias75015** [IGNF/geopf-extensions-openlayers#121]
Ajouter des marges et centrer la flèche de dépliement par rapport au titre : 

![image](https://github.com/user-attachments/assets/677c8ec6-a553-4985-b2b2-b6fd13c491ee)

Ajouter aussi une séparation horizontale comme sur la maquette

**Comment by azarz** [comment]
https://www.figma.com/design/s7gqdbxLRzPinQCRcoYXcT/Mise-en-DSFR-des-Widgets?node-id=904-33480&m=dev

**Comment by elias75015** [comment]
Voir si ces remarques peuvent être prises en compte via le travail fait ici : 
https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/290
