### ISSUE TITLE
style(LayerSwitcher): Changement bouton drag & drop

### ISSUE THREAD

**Issue by elias75015** [IGNF/geopf-extensions-openlayers#122]
Le bouton 6 points doit être remplacé par un bouton DSFR pour effectuer le drag & Drop : 

![image](https://github.com/user-attachments/assets/09b95603-14e7-4229-8fcd-81b95426b686)

par 

![image](https://github.com/user-attachments/assets/787ce40c-067f-4397-bd97-258bd691de30)

**Comment by azarz** [comment]
https://www.figma.com/design/s7gqdbxLRzPinQCRcoYXcT/Mise-en-DSFR-des-Widgets?node-id=877-15245&m=dev
