### ISSUE TITLE
style(general): mise à jour de tous les icones des widgets

### ISSUE THREAD

**Issue by elias75015** [IGNF/geopf-extensions-openlayers#129]
Mettre à jour les icones avec les icones choisis ici :

https://www.figma.com/design/s7gqdbxLRzPinQCRcoYXcT/Mise-en-DSFR-des-Widgets?node-id=1174-22881&m=dev

tIl en manque encore quelques uns, notamment ceux pour annoter la carte (ligne, marker, surface, modifier position, couleur...)

**Comment by azarz** [comment]
Première étape réalisée ici : https://github.com/IGNF/geopf-extensions-openlayers/pull/133

**Comment by elias75015** [comment]
Reste à faire ici : https://github.com/IGNF/geopf-extensions-openlayers/issues/37
