### ISSUE TITLE
style(positions): Ajouter un ascenseur (flèches) sur les positions relatives des widgets sur la carte

### ISSUE THREAD

**Issue by lowzonenose** [IGNF/geopf-extensions-openlayers#167]
Quand la liste des widgets, positionnés en relative, est trop longue par rapport à la hauteur ou largeur de la carte, on met en place un ascenseur, type flèche haut/bas ou gauche/droite
![image](https://github.com/user-attachments/assets/1aa6e5f4-d3b3-4e84-a811-5a63b74853b1)

**Comment by elias75015** [comment]
En attente maquette ascenseur

**Comment by azarz** [comment]
à fermer @elias75015
