### ISSUE TITLE
feat(layers): Meilleur rendu avec une transition fluide pour les tuiles 

### ISSUE THREAD

**Issue by lowzonenose** [IGNF/geopf-extensions-openlayers#168]
Remontée utilisateur : 

> quand je zoom/dezoom (rapidement) sur la carto en mode "normal" , j'ai un fond blanc
> en mode "plein ecran"  j'ai un fond noir.
> n'est-il pas possible d'avoir les couches supérieures (déja chargée du coup) en "pixelisées"  à la place des fonds unis? 

Pistes possibles : 

- https://openlayers.org/en/latest/apidoc/module-ol_source_Tile-TileSource.html
  > transition et interpolate

- https://openlayers.org/en/latest/apidoc/module-ol_layer_Tile-TileLayer.html
  > preload et cacheSize
  > Load low-resolution tiles up to preload levels. 0 means no preloading.
  > The internal tile cache size. This needs to be large enough to render two zoom levels worth of tiles.

**Comment by lowzonenose** [comment]
Ex. de configuration possible : 
```js
                           new ol.layer.GeoportalWMTS({
                                layer : "ORTHOIMAGERY.ORTHOPHOTOS",
                                olParams : {
                                    preload : 10,
                                    cacheSize : 1024,
                                    sourceParams : {
                                        transition : 0
                                    }
                                }
                            })
```

**Comment by azarz** [comment]
Pour ce qu'on n'a pas utilisé dans la PR, c'est-à dire ce qui est dans TileSource : 
- interpolate : à mon avis c'est par pour le cas remonté mais pour les zooms non entiers
- transition : c'est le fade in des tuiles, par défaut un peux doux en 250ms, à garder par défaut https://openlayers.org/en/latest/examples/tile-transitions.html sinon ça clignote c'est pas beau

Donc en somme c'est bien au niveau de TileLayer qu'il fallait agir.
