### ISSUE TITLE
fix(draggable): le mode draggable ne fonctionne pas correctement

### ISSUE THREAD

**Issue by lowzonenose** [IGNF/geopf-extensions-openlayers#174]
Le mode **draggable** ne fonctionne pas correctement lorsque les widgets sont en position **right** !?

> Problème quand on clique sur l'icone de détachement du menu.
> La fenêtre se retrouve coincée sur la droite. Je peux la déplacer que verticalement ou vers la droite
![image](https://github.com/user-attachments/assets/ec6be57d-2c41-4511-9608-bd969748ad63)

**Comment by elias75015** [comment]
C'est pas corrigé ça @azarz ?

**Comment by azarz** [comment]
si

**Comment by elias75015** [comment]
en fait non

**Comment by azarz** [comment]
ah

**Comment by elias75015** [comment]
En mode classique aussi. Il s'ajoute à ma liste de ce qui chie en mode classique

**Comment by azarz** [comment]
je vais fixer ça tkt
