### ISSUE TITLE
fix(LayerImport): Problème de ouverture/fermeture du panneau des résultats des getCap / MapBox

### ISSUE THREAD

**Issue by IGNFhc** [IGNF/geopf-extensions-openlayers#178]
Quand on importe une couche tuile vectorielle le panel se ferme et le bouton reste actif (même comportement pour une URL et un fichier local)
On ne peut alors plus ouvrir le widget.

**Comment by elias75015** [comment]
Le LayerImportPanel disparait à l'écran lorsqu'on importe tuiles vectorielles, alors qu'il est encore présent dans le DOM.

Le bouton lui reste en aria-pressed = true.

Aucune erreur en console (si ce n'est un cookie mal configuré), et en faisant du pas à pas, le panel disparait après l'exécution de fileReader.readAsText.

**Comment by azarz** [comment]
https://github.com/IGNF/geopf-extensions-openlayers/issues/34
