### ISSUE TITLE
Elevation Path panel position

### ISSUE THREAD

**Issue by IGNFhc** [IGNF/geopf-extensions-openlayers#179]
![image](https://github.com/user-attachments/assets/65188829-7575-4741-8566-bd618a8a1eaf)

**Comment by IGNFhc** [comment]
la fenêtre est hors de la carte

**Comment by elias75015** [comment]
ALED JP je comprends pas comment le positionnement du dialog est calculé. Je veux bien que tu me montres à ton retour.

**Comment by elias75015** [comment]
Corrigé par https://github.com/IGNF/geopf-extensions-openlayers/pull/201
