### ISSUE TITLE
feat(LocationSelector): les modales de type "Location Selector" s'ouvrent en position fixe

### ISSUE THREAD

**Issue by elias75015** [IGNF/geopf-extensions-openlayers#220]
Faire ce qui a été fait sur #200 pour les panels locationSelector : 
- itineraire
- isochrone

**Comment by elias75015** [comment]
En fait ca ne le fait que sur l'instance de dev/prod de l'entrée carto...
Mais pas sur la démo github.io ni sur les extensions...

Un truc a dû être fait non ?

**Comment by azarz** [comment]
heu je n'ai pas du tout touché aux location selector. C'est quoi la version sur la dev/prod de l'entrée carto ?

**Comment by azarz** [comment]
Sur la dev/prod, si c'est la 1.0.0, c'est la v193 des exts mergée le 11/10. LA PR sur le positionnement des fenêtres est la 201 et a été mergée le 15/10.

Du coup le problème sera résolu en mettant à jour les extensions
