### ISSUE TITLE
fix(GFI): exception sur des données importées de type GPX ou KML !

### ISSUE THREAD

**Issue by lowzonenose** [IGNF/geopf-extensions-openlayers#221]
![image](https://github.com/user-attachments/assets/abdccd3c-8700-4f65-892d-c1f708882751)

**Comment by IGNFhc** [comment]
Je n'arrive pas à reproduire en local ....

**Comment by IGNFhc** [comment]
https://github.com/IGNF/geopf-extensions-openlayers/pull/222
