### ISSUE TITLE
bug(searchengine): le panel des résultats d'autocomplétion est mal positionné

### ISSUE THREAD

**Issue by elias75015** [IGNF/geopf-extensions-openlayers#307]
Pour reproduire : taper une requete dans une barre de recherche positionnée dans un coin.

Le panel des résultats ne se positionne pas sous la barre de recherche mais en absolu au dessus :
![Image](https://github.com/user-attachments/assets/3a713055-cbc3-4a0c-99ad-de73c30f6777)

**Comment by elias75015** [comment]
🎁 @azarz

**Comment by azarz** [comment]
c'est noël avant l'heure merci
