### ISSUE TITLE
bug(geoco-inv): l'interaction par cercle ne fonctionne pas en mode classique

### ISSUE THREAD

**Issue by elias75015** [IGNF/geopf-extensions-openlayers#314]
Pour reproduire : 
geocodage inverse mode classique par cercle

-> le cercle disparait immédiatement

**Comment by azarz** [comment]
Je n'arrive pas à reproduire en suivant ces étapes

**Comment by elias75015** [comment]
OK j'ai craqué, je ne reproduis pas
