### ISSUE TITLE
fix(LayerImport) : Le panneau des résultats du vecteur tuilé et getCapabilities ne s'affiche pas correctement

### ISSUE THREAD

**Issue by lowzonenose** [IGNF/geopf-extensions-openlayers#34]
Le panneau des résultats de l'import du vecteur tuilé 
* ne s'affiche pas sur le thème dsfr car les dimensions du panneau sont nulles (l'éditeur est bien présent !)
* s'affiche en dehors de la carte sur le thème classic

Test : 
```text
> npm run samples:modules
puis ouvrir l'exemple : 
* https://localhost:8080/samples/tests/LayerImport/pages-ol-layerimport-modules-default.html
* https://localhost:8080/samples/tests/LayerImport/pages-ol-layerimport-modules-dsfr-default.html
télécharger le fichier en local : https://data.geopf.fr/annexes/ressources/vectorTiles/styles/PLAN.IGN/gris.json
importer
```
Comportement attendu : 
> ouverture d'un éditeur de style visible !

**Comment by elias75015** [comment]
Il faut également faire apparaitre la modale des résultats de la requete aux getCap (n'est pas au DSFR)

Il suffirait d'ajouter des classes pour que ca marche (+ copier itinéraire)
