### ISSUE TITLE
fix(Drawing): Affichage du panneau des outils de dessin

### ISSUE THREAD

**Issue by lowzonenose** [IGNF/geopf-extensions-openlayers#37]
Divers problème sur l'outil de dessin.

### En mode DSFR :

1. les icones ne sont pas bons
- [ ] ils sont à mettre à niveau à partir de cette bibliothèque d'icones : https://www.figma.com/design/HzI4HxsNl6U63XQ39XP8rj/Ic%C3%B4nes-DSFR%40IGN?node-id=18-5299&t=q4SPTdPCQBvpiQGn-1

2. les fenêtres secondaires n'ont pas été implémentées en mode DSFR : 
- [ ] les tooltips liées aux features (écrire du texte affichable dans une pop-up quand on clique sur la feature)
- [ ] la fenêtre de modification de couleur pour les ponctuels
![image](https://github.com/user-attachments/assets/9ef5a041-4c8b-4eaa-98e5-f4ff20cf5dd5)
- [ ] la fenêtre de modification de style pour les surfaces ou linéaires 
![image](https://github.com/user-attachments/assets/c8dd8e3b-7554-4b5d-bf7f-44f4c697b896)
- [ ] la fenêtre de modification du texte inscrit sur la carte

### Dans les deux modes : 
- [ ] Changement de style (espacement) lorsque l'on clique sur un icone de dessin : 
![image](https://github.com/IGNF/geoportal-extensions-openlayers/assets/10401006/6362b03b-805d-4b74-9ef6-3659140e092b) ![image](https://github.com/IGNF/geoportal-extensions-openlayers/assets/10401006/c078ab82-f0fe-406b-90ee-bd9589c865e6)

Comportement attendu:
> Pas de changement de style !

**Comment by elias75015** [comment]
Kristell doit faire une proposition sur le figma, n'hésite pas à regarder régulièrement s'il y a du noouveau (ici par ex : https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/22)

**Comment by elias75015** [comment]
https://www.figma.com/design/HzI4HxsNl6U63XQ39XP8rj/Ic%C3%B4nes-DSFR%40IGN?node-id=18-5299&t=q4SPTdPCQBvpiQGn-1

A mettre à niveau à partir de cette bibliothèque d'icones.

**Comment by elias75015** [comment]
![drawing-tools-dsfr](https://github.com/user-attachments/assets/2e184873-4c75-4dda-b3a0-06d52bce2f70)

**Comment by elias75015** [comment]
@azarz si t'as un peu de temps à ton retour de cavances, ça m'a modérément saoulé en fait

**Comment by elias75015** [comment]
J'ai mis à jour la description du ticket pour référencer une bonne partie du reste à faire sur le widget
